"""Checklist Table

Revision ID: 101b9ab2552c
Revises: 2c2b3497bd8e
Create Date: 2021-02-05 21:46:14.973401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101b9ab2552c'
down_revision = '2c2b3497bd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist')
    # ### end Alembic commands ###
