"""added 'is_original' to checklist table

Revision ID: 7a6e79dd465b
Revises: fdaffcbca648
Create Date: 2021-02-09 09:41:29.705663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6e79dd465b'
down_revision = 'fdaffcbca648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist', sa.Column('is_original', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist', 'is_original')
    # ### end Alembic commands ###
