"""recreated all tables

Revision ID: fdaffcbca648
Revises: 
Create Date: 2021-02-08 22:01:47.501620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaffcbca648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_row',
    sa.Column('rownum', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('Criteria', sa.String(length=240), nullable=True),
    sa.Column('Comment', sa.String(length=240), nullable=True),
    sa.Column('Reference', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('rownum'),
    sa.UniqueConstraint('Comment'),
    sa.UniqueConstraint('Criteria')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('dsc_number', sa.String(length=20), nullable=True),
    sa.Column('recipient', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modified_row',
    sa.Column('row_number', sa.String(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('Criteria', sa.String(length=240), nullable=True),
    sa.Column('Comment', sa.String(length=240), nullable=True),
    sa.Column('Ceference', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('row_number'),
    sa.UniqueConstraint('Comment'),
    sa.UniqueConstraint('Criteria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modified_row')
    op.drop_table('checklist')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('original_row')
    # ### end Alembic commands ###
