"""added Row table and its relationhip with the checklist table.

Revision ID: fef29bd9e440
Revises: 101b9ab2552c
Create Date: 2021-02-08 14:03:33.166099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef29bd9e440'
down_revision = '101b9ab2552c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('criteria', sa.String(length=240), nullable=True),
    sa.Column('comment', sa.String(length=240), nullable=True),
    sa.Column('reference', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment'),
    sa.UniqueConstraint('criteria')
    )
    op.add_column('project', sa.Column('recipient', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'recipient')
    op.drop_table('row')
    # ### end Alembic commands ###
